# Generated by Django 4.2.16 on 2024-10-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country_name", models.CharField(max_length=50, null=True)),
                ("country_description", models.TextField()),
                ("country_code", models.CharField(max_length=3, null=True)),
                (
                    "currency_symbol",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
            ],
            options={"verbose_name_plural": "Country Master",},
        ),
        migrations.CreateModel(
            name="GstSchemeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gst_scheme_name", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Gst Scheme Master",},
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=50, null=True)),
                ("state_description", models.TextField()),
                ("state_code", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "country_details",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_details",
                        to="global_master.country",
                    ),
                ),
            ],
            options={"verbose_name_plural": "State Master",},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city_name", models.CharField(max_length=50, null=True)),
                ("city_description", models.TextField(blank=True, null=True)),
                ("city_code", models.CharField(blank=True, max_length=5, null=True)),
                ("city_pincode", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "city_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "city_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "state_details",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_details",
                        to="global_master.state",
                    ),
                ),
            ],
            options={"verbose_name_plural": "City Master",},
        ),
    ]
