# Generated by Django 4.2.16 on 2024-10-06 16:11

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("global_master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_name", models.CharField(max_length=50, null=True)),
                ("brand_description", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Brand Master",},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_name", models.CharField(max_length=50, null=True)),
                ("category_description", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Category Master",},
        ),
        migrations.CreateModel(
            name="CompanyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("company_alias", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("company_mobile", models.CharField(max_length=13, null=True)),
                ("company_phone_number", models.CharField(max_length=13, null=True)),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("company_website", models.URLField(blank=True, null=True)),
                (
                    "company_address1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "company_address2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("city", models.CharField(max_length=40, null=True)),
                (
                    "company_pincode",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                ("fy_starts", models.DateField(null=True)),
                (
                    "currency_symbol",
                    models.CharField(default="₹", max_length=4, null=True),
                ),
                (
                    "formal_currency_name",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("is_stock_maintained", models.BooleanField(default=True, null=True)),
                ("is_vat_enabled", models.BooleanField(default=False, null=True)),
                ("vat_number", models.CharField(blank=True, max_length=15, null=True)),
                ("is_gst_enabled", models.BooleanField(default=False, null=True)),
                ("gst_number", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "opening_balance",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=20),
                ),
                (
                    "company_pan_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "company_tin_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "company_bank_acct_holder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_bank_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "company_bank_account_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "company_bank_ifsc_code",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="global_master.country",
                    ),
                ),
                (
                    "gst_scheme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="global_master.gstschememaster",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="global_master.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Company Master",},
        ),
        migrations.CreateModel(
            name="HsnMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hsn_code", models.CharField(max_length=10, null=True)),
                ("hsn_description", models.TextField()),
                ("tax_rate", models.DecimalField(decimal_places=3, max_digits=5)),
                (
                    "c_gst",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "s_gst",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hsn_company",
                        to="api.companymaster",
                    ),
                ),
            ],
            options={"verbose_name_plural": "HSN Master",},
        ),
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(max_length=100, null=True)),
                ("product_description", models.TextField(blank=True, null=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        default=api.models.create_unique_barcode,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sku_code",
                    models.CharField(
                        blank=True,
                        default=api.models.create_unique_barcode,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="products_images/"
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "brand_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brand_details",
                        to="api.brand",
                    ),
                ),
                (
                    "category_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_details",
                        to="api.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_master_company",
                        to="api.companymaster",
                    ),
                ),
                (
                    "hsn_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hsn_details",
                        to="api.hsnmaster",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Master",},
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_name", models.CharField(max_length=50, null=True)),
                ("unit_description", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_company",
                        to="api.companymaster",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Unit Master",},
        ),
        migrations.CreateModel(
            name="ProductsImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="products_images/")),
                ("is_main", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_images_company",
                        to="api.companymaster",
                    ),
                ),
                (
                    "product_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="api.productmaster",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="productmaster",
            name="unit_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unit_details",
                to="api.unit",
            ),
        ),
        migrations.CreateModel(
            name="PartyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("party_type", models.CharField(max_length=100, null=True)),
                ("party_type_description", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party_type_company",
                        to="api.companymaster",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Party Type Master",},
        ),
        migrations.CreateModel(
            name="PartyLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("party_name", models.CharField(max_length=100)),
                ("party_alias", models.CharField(blank=True, max_length=50, null=True)),
                ("party_address", models.TextField(blank=True, null=True)),
                (
                    "party_phone_number",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "party_mobile_number",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "party_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "party_gst_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party_ledger_company",
                        to="api.companymaster",
                    ),
                ),
                (
                    "party_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="global_master.state",
                    ),
                ),
                (
                    "party_type_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party_type_details",
                        to="api.partytype",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Party Master",},
        ),
        migrations.CreateModel(
            name="CustomerMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mobile_number", models.CharField(max_length=13, null=True)),
                ("alternate_mobile_number", models.CharField(max_length=13, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("anniversary", models.DateField(blank=True, null=True)),
                ("customer_address", models.TextField(blank=True, null=True)),
                (
                    "city_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_city_details",
                        to="global_master.city",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_master_company",
                        to="api.companymaster",
                    ),
                ),
                (
                    "country_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_country_details",
                        to="global_master.country",
                    ),
                ),
                (
                    "state_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_state_details",
                        to="global_master.state",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Customer Master",},
        ),
        migrations.AddField(
            model_name="category",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_company",
                to="api.companymaster",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="brand_company",
                to="api.companymaster",
            ),
        ),
        migrations.AddIndex(
            model_name="productmaster",
            index=models.Index(
                fields=["product_name", "barcode", "sku_code"],
                name="api_product_product_b65b6d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmaster",
            constraint=models.UniqueConstraint(
                fields=("company", "barcode"), name="unique_company_barcode"
            ),
        ),
        migrations.AddConstraint(
            model_name="productmaster",
            constraint=models.UniqueConstraint(
                fields=("company", "sku_code"), name="unique_company_sku_code"
            ),
        ),
    ]
