# Generated by Django 4.2.16 on 2024-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="app_user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "admin"),
                    ("staff", "staff"),
                    ("manager", "manager"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
